### PR TITLE
Improve handling of UTF-8

### PR DESCRIPTION
**Pull request by RBA900826**
Improve handling of UTF-8 characters for Load JSON From File keyword

### CODE REVIEW

**Comment by RBA900826** [comment]
Can we please check if we can include this RBA900826 pull request into master branch?

**Comment by wichy13** [comment]
> Can we please check if we can include this RBA900826 pull request into master branch?

Screen Shot 2562-10-12 at 16 34 37
Screen Shot 2562-10-12 at 16 34 57

**Comment by pencherek** [comment]
I use JSONLibrary in my robot framework project and when I use "Load JSON From File" on a file in utf8 with french character like "é" I get a error, I fixed it up by modifing the keyword, Iwould like to know if this correctif is good. I add 
import io
@keyword('Load JSON From File')
    def load_json_from_file(self, file_name, encoding):    
        """Load JSON from file.

        Return json as a dictionary object.

        Arguments:
            - file_name: absolute json file name
            - encoding: encoding of the file

        Return json object (list or dictionary)

        Examples:
        | ${result}=  |  Load Json From File  | /path/to/file.json |
        """
        logger.debug("Check if file exists")
        if os.path.isfile(file_name) is False:
            logger.error("JSON file: " + file_name + " not found")
            raise IOError
        with io.open(file_name,mode='r',encoding=encoding) as json_file:
            data = json.load(json_file)
        return data

**Comment by elrandira** [comment]
This change was included as part of https://github.com/robotframework-thailand/robotframework-jsonlibrary/pull/35. Thanks for the fix!

**Pull request closed without merging**
