### PR TITLE
New keyword 'Convert string to json' and some fixes

### PR DESCRIPTION
**Pull request by dwapstra**
Convert string to json object using json.loads()
Fixes for python 3 support
Fix setup version lookup

### CODE REVIEW

**Comment by asyrjasalo** [comment]
@nottyo: Any news on getting Python 3 support (merged) to the robotframework-jsonlibrary mainline?

**Comment by kowalpy** [comment]
Converting string to json would be very useful. I hope it will be merged and released soon.

**Comment by fpagliughi** [comment]
Will this be merged?

**Comment by nkontio** [comment]
I think this update and base code should soon be moved to some new project since @nottyo is out of reach. Add him there as master too so should not be problem if he ever takes look at this code again.
pip3 installing broken version should have been fixed long time ago.

**Comment by cydashboardthqa** [comment]
I'm so sorry about that since I don't have enough time to maintain this project 🙏

**Comment by nottyo** [comment]
I'm so sorry about that since I don't have enough time to maintain this project 🙏 Anyway, I'll merge this PR thanks.

**Comment by nkontio** [comment]
> I'm so sorry about that since I don't have enough time to maintain this project  Anyway, I'll merge this PR thanks.

Thank you!
Could you consider think giving admin rights to someone you know who has time?
Or to robot framework foundation? This is handy library would be sad if the development stops.

**Comment by nottyo** [comment]
Ok. I'll consider it soon

**Pull request merged**
