### PR TITLE
Release 0.4

### PR DESCRIPTION
**Pull request by elrandira**
covers #38

### CODE REVIEW

**Comment by elrandira** [comment]
Hi @ohmrefresh,

if this is fine with you, could you merge this pull request, set a new tag and release and perform delivery of robotframework-jsonlibrary v0.4.0 to Pypi? It looks like you use Travis and I am unfamiliar with this API.

**Comment by ohmrefresh** [comment]
@elrandira i found some error on travis https://app.travis-ci.com/github/robotframework-thailand/robotframework-jsonlibrary/builds/250988675

**Comment by elrandira** [comment]
thanks, i'll try to solve this.

**Comment by elrandira** [comment]
quick analysis, it seems the issue is unrelated to this package but setup-tools would be the culprit. It is failling during _pip install -r requirements.txt_. Other package publishers had the same issue:
- https://github.com/pypa/setuptools/issues/3293
- https://github.com/pypa/setuptools/issues/3102

and travis was switched from python 2.7 to 3.7 while solving issue #10.

I will try to get a Travis on my own repo. I need to understand what's going on

**Pull request merged**
