### PR TITLE
update doc on known issue with space in JSONPath expression

### PR DESCRIPTION
**Pull request by idxn**
@nottyo I've experienced the issue with space in JSONPath. I think it is worth to point this out in the document so people using this would avoid the space.

### CODE REVIEW

**Comment by idxn** [comment]
@nottyo  how's thing going? Is there anything I can do to get this accepted?

**Comment by nottyo** [comment]
@idxn Please do not change the keyword documentation manually (docs/JSONLibrary.html) It's generated automatically by Travis-ci.

**Comment by idxn** [comment]
emm ok. thanks. I haven't seen any failed on the travis so I'm not aware of it.

**Comment by idxn** [comment]
@nottyo done

**Comment by idxn** [comment]
@nottyo just a head up. do you want anything else to get this through?

**Review by Tset-Noitamotua — COMMENTED** [review]
@idxn  Good to know, thank you!

maybe file an issue for that request so it would be easier for other to know about this issue.

**Pull request merged**
