### PR TITLE
Fixes for #5, #6, #25, #26, #29, #30

### PR DESCRIPTION
**Pull request by elrandira**
This is my proposal to merge existing pull request
- pull request #32 for issue #29 by @otemek
- Pull request #34 by @pencherek

And solves the following issues:
- issue #10 solved by Marcin Koperski @IlfirinPL in his own branch
- issue #5
- issue #6
- issue #25
- issue #26 
- issue #30

Add new keywords:
- Dump JSON To File (issue #29)
- Should Have Value In JSON
- Should Not Have Value In JSON
- 
If you agree with these changes, thanks to accepts the pull request and update the delivery on Pypi

### CODE REVIEW

**Comment by pencherek** [comment]
Ok, good idea, just how do I do that, I don't really know how to do that on github

**Comment by elrandira** [comment]
Hi, only the repo owner and the approved contributors can accept a pull request. Buttons should be visible to them.

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/approving-a-pull-request-with-required-reviews

**Comment by pencherek** [comment]
I think the owner droped it, the repo got any update for year and in the issue (bug) page, he has not posted for a long time

**Comment by pencherek** [comment]
Perhaps we sould create a new repository and a new entry for pip on Pypi

**Comment by elrandira** [comment]
Yes that came to my mind, I'll look into it. In the meantime, my branch can be used by anyone:

git install git+https://github.com/elrandira/robotframework-jsonlibrary

**Comment by pencherek** [comment]
So your branch is the most updated ?
If so I have a idea for a update for the "Get Value From Json" keyword,
we will need perhaps to use a better JSONPATH interpreter, during my work with robot framework, some complex JSONPATH were not working as expected

**Comment by nottyo** [comment]
@elrandira I'm sorry to for my late reply. I'm not working for this project anymore. However, I'll add you to be one the owner of this repository so that you can manage changes from now on.

**Comment by elrandira** [comment]
Thanks @nottyo, I'll look into it :)

@pencherek, eventually you can open an issue to keep track on your idea.

**Pull request merged**
